lua: build: link against liblua
ldd reports many errors regarding missing symbols because the library
is not linked against liblua.

root@openwrt ~ # ldd /usr/lib/lua/ubus.so
        ldd (0x7fa9d40000)
        libubus.so.20260523 => /lib/libubus.so.20260523 (0x7fa9dd6000)
        libubox.so.20260213 => /lib/libubox.so.20260213 (0x7fa9d2e000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7fa9cfd000)
        libc.so => ldd (0x7fa9d40000)
Error relocating /usr/lib/lua/ubus.so: lua_touserdata: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushlightuserdata: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_isnumber: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_ref: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_objlen: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_getfield: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_next: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_gettop: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_tointeger: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_checklstring: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushnumber: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_remove: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_setfield: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushvalue: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushnil: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_tonumber: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_settop: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushfstring: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_tolstring: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_type: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushboolean: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_settable: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_setmetatable: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_rawseti: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_optlstring: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_newmetatable: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_newuserdata: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_call: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_error: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_gettable: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushstring: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_argerror: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_checkinteger: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_checkudata: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_rawgeti: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_optinteger: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_rawset: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_checktype: symbol not found
Error relocating /usr/lib/lua/ubus.so: luaL_register: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_toboolean: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_createtable: symbol not found
Error relocating /usr/lib/lua/ubus.so: lua_pushinteger: symbol not found
root@openwrt ~ #

We have to link the lua ubus library against liblua.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>